/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  EvmBridgeMediator,
  EvmBridgeMediatorInterface,
} from "../EvmBridgeMediator";

const _abi = [
  {
    inputs: [],
    name: "getNonce",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "sendMessage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "nonce",
            type: "uint256",
          },
          {
            internalType: "uint8",
            name: "opType",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "srcChainId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "destChainId",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "destAddress",
            type: "string",
          },
          {
            internalType: "address",
            name: "contractAddress",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "tokenId",
            type: "uint256",
          },
        ],
        indexed: false,
        internalType: "struct BridgeMediator.Message",
        name: "message",
        type: "tuple",
      },
    ],
    name: "MessageSend",
    type: "event",
  },
] as const;

export class EvmBridgeMediator__factory {
  static readonly abi = _abi;
  static createInterface(): EvmBridgeMediatorInterface {
    return new Interface(_abi) as EvmBridgeMediatorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): EvmBridgeMediator {
    return new Contract(address, _abi, runner) as unknown as EvmBridgeMediator;
  }
}
