[package]
name = "icrc-7"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.15"
ic-cdk-timers = "0.7"
ic-cdk-macros = "0.13.2"
serde = "1.0"
serde_json = "1.0"
lazy_static = "1.4"
