/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "./common";

export interface EvmBridgeContractInterface extends Interface {
  getEvent(nameOrSignatureOrTopic: "messageSend"): EventFragment;
}

export namespace messageSendEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    message: string
  ];
  export type OutputTuple = [from: string, to: string, message: string];
  export interface OutputObject {
    from: string;
    to: string;
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EvmBridgeContract extends BaseContract {
  connect(runner?: ContractRunner | null): EvmBridgeContract;
  waitForDeployment(): Promise<this>;

  interface: EvmBridgeContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "messageSend"
  ): TypedContractEvent<
    messageSendEvent.InputTuple,
    messageSendEvent.OutputTuple,
    messageSendEvent.OutputObject
  >;

  filters: {
    "messageSend(address,address,string)": TypedContractEvent<
      messageSendEvent.InputTuple,
      messageSendEvent.OutputTuple,
      messageSendEvent.OutputObject
    >;
    messageSend: TypedContractEvent<
      messageSendEvent.InputTuple,
      messageSendEvent.OutputTuple,
      messageSendEvent.OutputObject
    >;
  };
}
