/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EvmBridgeContract } from "./EvmBridgeContract";
export * as factories from "./factories";
export { EvmBridgeContract__factory } from "./factories/EvmBridgeContract__factory";
